"""empty message

Revision ID: a5e746173d9c
Revises: add0a4d63138
Create Date: 2020-05-19 09:57:47.671817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5e746173d9c'
down_revision = 'add0a4d63138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=8), nullable=True))

    # ### end Alembic commands ###
